config/routes.rb
Rails.application.routes.draw do
  resources :places_referenceds
  resources :stops
  resources :argonautica_people
  resources :inscription, :site, :marker, :koina, :priesthood, :role, :individual, :groupings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '' => 'net#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/argonautica_person.rb
class ArgonauticaPerson < ActiveRecord::Base
  belongs_to :origin,  :class_name => 'Site', :foreign_key => 'origin_id'
  has_many :stops_people
  has_and_belongs_to_many :places_referenceds
end

app/models/grouping.rb
class Grouping < ActiveRecord::Base
  belongs_to :inscription
  belongs_to :priesthood
end

app/models/individual.rb
class Individual < ActiveRecord::Base
  belongs_to :inscription
  belongs_to :site,  :class_name => 'Site', :foreign_key => 'site_id'
  belongs_to :site_origin,  :class_name => 'Site', :foreign_key => 'site_origin_id'
  has_many :roles
  has_many :places_referenceds
end

app/models/inscription.rb
class Inscription < ActiveRecord::Base
    has_many :koinas
    has_many :individuals
    has_and_belongs_to_many :priesthoods
    has_many :groupings
    has_many :priesthoods, through: :groupings
    belongs_to :find_spot,  :class_name => 'Site', :foreign_key => 'find_spot_id'
    has_attached_file :picture
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
end

app/models/koina.rb
class Koina < ActiveRecord::Base
  belongs_to :site
  belongs_to :inscription
end

app/models/marker.rb
class Marker < ActiveRecord::Base
  belongs_to :site
end

app/models/places_referenced.rb
class PlacesReferenced < ActiveRecord::Base
  belongs_to :place_referenced,  :class_name => 'Site', :foreign_key => 'place_referenced_id'
  belongs_to :previous_place,  :class_name => 'Site', :foreign_key => 'previous_place_id'
  belongs_to :next_place,  :class_name => 'Site', :foreign_key => 'next_place_id'
  belongs_to :referenced_by, :class_name => 'Individual', :foreign_key => 'referenced_by_id'
  has_and_belongs_to_many :argonautica_people
  has_many :stops_people
  has_many :argonautica_people
  accepts_nested_attributes_for :stops_people, :allow_destroy => true
  accepts_nested_attributes_for :argonautica_people, :allow_destroy => true

end

app/models/priesthood.rb
class Priesthood < ActiveRecord::Base
    belongs_to :role
    has_and_belongs_to_many :inscriptions
    belongs_to :location,  :class_name => 'Site', :foreign_key => 'location_id'
    has_many :groupings
    has_many :inscriptions, through: :groupings
    accepts_nested_attributes_for :groupings, :allow_destroy => true
    accepts_nested_attributes_for :inscriptions, :allow_destroy => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :individual
  has_many :priesthoods
end

app/models/site.rb
class Site < ActiveRecord::Base
    has_many :markers
    has_many :koinas
    has_many :individuals
    has_many :priesthoods
    has_many :inscriptions
    has_many :argonautica_people
    has_many :stops
    has_many :places_referenceds
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  belongs_to :place_of_stop,  :class_name => 'Site', :foreign_key => 'place_of_stop_id'
  belongs_to :previous_place,  :class_name => 'Site', :foreign_key => 'previous_place_id'
  belongs_to :next_place,  :class_name => 'Site', :foreign_key => 'next_place_id'
  has_many :stops_people
  has_many :argonautica_people
  accepts_nested_attributes_for :stops_people, :allow_destroy => true
  accepts_nested_attributes_for :argonautica_people, :allow_destroy => true
end

app/models/stops_person.rb
class StopsPerson < ActiveRecord::Base
    belongs_to :argonautica_person
    belongs_to :stop
    belongs_to :places_referenced
    belongs_to :crew,  :class_name => 'ArgonauticaPerson', :foreign_key => 'crew_id'
    belongs_to :ritual_person,  :class_name => 'ArgonauticaPerson', :foreign_key => 'ritual_person_id'
end

app/controllers/stops_controller.rb
class StopsController < InheritedResources::Base

  private

    def stop_params
      params.require(:stop).permit(:ritual_person_id, :ritual_person, :stops_people_id, :stops_people, :place_of_stop, :place_of_stop_id, :previous_place, :previous_place_id, :next_place, :next_place_id, :type_of_stop, :line_number, :ritual, :ritual_deity)
    end
end

app/helpers/grouping_helper.rb
module GroupingHelper
end

app/helpers/individual_helper.rb
module IndividualHelper
end

app/helpers/koina_helper.rb
module KoinaHelper
end

app/helpers/marker_helper.rb
module MarkerHelper
end

app/helpers/net_helper.rb
module NetHelper
end

app/helpers/priesthood_helper.rb
module PriesthoodHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/stops/_form.html.erb
<%= form_for(@stop) do |f| %>
  <% if @stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
      <% @stop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_of_stop %><br>
    <%= f.text_field :type_of_stop %>
  </div>
  <div class="field">
    <%= f.label :line_number %><br>
    <%= f.text_field :line_number %>
  </div>
  <div class="field">
    <%= f.label :ritual %><br>
    <%= f.text_field :ritual %>
  </div>
  <div class="field">
    <%= f.label :ritual_deity %><br>
    <%= f.text_field :ritual_deity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stops/edit.html.erb
<h1>Editing Stop</h1>

<%= render 'form' %>

<%= link_to 'Show', @stop %> |
<%= link_to 'Back', stops_path %>

app/views/stops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stops</h1>

<table>
  <thead>
    <tr>
      <th>Type of stop</th>
      <th>Line number</th>
      <th>Ritual</th>
      <th>Ritual deity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= stop.type_of_stop %></td>
        <td><%= stop.line_number %></td>
        <td><%= stop.ritual %></td>
        <td><%= stop.ritual_deity %></td>
        <td><%= link_to 'Show', stop %></td>
        <td><%= link_to 'Edit', edit_stop_path(stop) %></td>
        <td><%= link_to 'Destroy', stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stop', new_stop_path %>

app/views/stops/new.html.erb
<h1>New Stop</h1>

<%= render 'form' %>

<%= link_to 'Back', stops_path %>

app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type of stop:</strong>
  <%= @stop.type_of_stop %>
</p>

<p>
  <strong>Line number:</strong>
  <%= @stop.line_number %>
</p>

<p>
  <strong>Ritual:</strong>
  <%= @stop.ritual %>
</p>

<p>
  <strong>Ritual deity:</strong>
  <%= @stop.ritual_deity %>
</p>

<%= link_to 'Edit', edit_stop_path(@stop) %> |
<%= link_to 'Back', stops_path %>