config/routes.rb
Rails.application.routes.draw do
  resources :places_referenceds
  resources :stops
  resources :argonautica_people
  resources :inscription, :site, :marker, :koina, :priesthood, :role, :individual, :groupings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '' => 'net#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/grouping.rb
class Grouping < ActiveRecord::Base
  belongs_to :inscription
  belongs_to :priesthood
end

app/models/individual.rb
class Individual < ActiveRecord::Base
  belongs_to :inscription
  belongs_to :site,  :class_name => 'Site', :foreign_key => 'site_id'
  belongs_to :site_origin,  :class_name => 'Site', :foreign_key => 'site_origin_id'
  has_many :roles
  has_many :places_referenceds
end

app/models/inscription.rb
class Inscription < ActiveRecord::Base
    has_many :koinas
    has_many :individuals
    has_and_belongs_to_many :priesthoods
    has_many :groupings
    has_many :priesthoods, through: :groupings
    belongs_to :find_spot,  :class_name => 'Site', :foreign_key => 'find_spot_id'
    has_attached_file :picture
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
end

app/models/koina.rb
class Koina < ActiveRecord::Base
  belongs_to :site
  belongs_to :inscription
end

app/models/marker.rb
class Marker < ActiveRecord::Base
  belongs_to :site
end

app/models/places_referenced.rb
class PlacesReferenced < ActiveRecord::Base
  belongs_to :place_referenced,  :class_name => 'Site', :foreign_key => 'place_referenced_id'
  belongs_to :previous_place,  :class_name => 'Site', :foreign_key => 'previous_place_id'
  belongs_to :next_place,  :class_name => 'Site', :foreign_key => 'next_place_id'
  belongs_to :referenced_by, :class_name => 'Individual', :foreign_key => 'referenced_by_id'
  has_and_belongs_to_many :argonautica_people
  has_many :stops_people
  has_many :argonautica_people
  accepts_nested_attributes_for :stops_people, :allow_destroy => true
  accepts_nested_attributes_for :argonautica_people, :allow_destroy => true

end

app/models/priesthood.rb
class Priesthood < ActiveRecord::Base
    belongs_to :role
    has_and_belongs_to_many :inscriptions
    belongs_to :location,  :class_name => 'Site', :foreign_key => 'location_id'
    has_many :groupings
    has_many :inscriptions, through: :groupings
    accepts_nested_attributes_for :groupings, :allow_destroy => true
    accepts_nested_attributes_for :inscriptions, :allow_destroy => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :individual
  has_many :priesthoods
end

app/models/site.rb
class Site < ActiveRecord::Base
    has_many :markers
    has_many :koinas
    has_many :individuals
    has_many :priesthoods
    has_many :inscriptions
    has_many :argonautica_people
    has_many :stops
    has_many :places_referenceds
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  belongs_to :place_of_stop,  :class_name => 'Site', :foreign_key => 'place_of_stop_id'
  belongs_to :previous_place,  :class_name => 'Site', :foreign_key => 'previous_place_id'
  belongs_to :next_place,  :class_name => 'Site', :foreign_key => 'next_place_id'
  has_many :stops_people
  has_many :argonautica_people
  accepts_nested_attributes_for :stops_people, :allow_destroy => true
  accepts_nested_attributes_for :argonautica_people, :allow_destroy => true
end

app/models/stops_person.rb
class StopsPerson < ActiveRecord::Base
    belongs_to :argonautica_person
    belongs_to :stop
    belongs_to :places_referenced
    belongs_to :crew,  :class_name => 'ArgonauticaPerson', :foreign_key => 'crew_id'
    belongs_to :ritual_person,  :class_name => 'ArgonauticaPerson', :foreign_key => 'ritual_person_id'
end

app/controllers/argonautica_people_controller.rb
class ArgonauticaPeopleController < InheritedResources::Base

  private

    def argonautica_person_params
      params.require(:argonautica_person).permit(:name, :origin_id, :origin, :tribe, :created_at, :updated_at)
    end
end

app/helpers/argonautica_people_helper.rb
module ArgonauticaPeopleHelper
end

app/helpers/grouping_helper.rb
module GroupingHelper
end

app/helpers/individual_helper.rb
module IndividualHelper
end

app/helpers/koina_helper.rb
module KoinaHelper
end

app/helpers/marker_helper.rb
module MarkerHelper
end

app/helpers/net_helper.rb
module NetHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/argonautica_people/_form.html.erb
<%= form_for(@argonautica_person) do |f| %>
  <% if @argonautica_person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@argonautica_person.errors.count, "error") %> prohibited this argonautica_person from being saved:</h2>

      <ul>
      <% @argonautica_person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :origin_id %><br>
    <%= f.text_field :origin_id %>
  </div>
  <div class="field">
    <%= f.label :tribe %><br>
    <%= f.text_field :tribe %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/argonautica_people/edit.html.erb
<h1>Editing Argonautica Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @argonautica_person %> |
<%= link_to 'Back', argonautica_people_path %>

app/views/argonautica_people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Argonautica People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Origin</th>
      <th>Tribe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @argonautica_people.each do |argonautica_person| %>
      <tr>
        <td><%= argonautica_person.name %></td>
        <td><%= argonautica_person.origin %></td>
        <td><%= argonautica_person.tribe %></td>
        <td><%= link_to 'Show', argonautica_person %></td>
        <td><%= link_to 'Edit', edit_argonautica_person_path(argonautica_person) %></td>
        <td><%= link_to 'Destroy', argonautica_person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Argonautica person', new_argonautica_person_path %>

app/views/argonautica_people/new.html.erb
<h1>New Argonautica Person</h1>

<%= render 'form' %>

<%= link_to 'Back', argonautica_people_path %>

app/views/argonautica_people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @argonautica_person.name %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @argonautica_person.origin %>
</p>

<p>
  <strong>Tribe:</strong>
  <%= @argonautica_person.tribe %>
</p>

<%= link_to 'Edit', edit_argonautica_person_path(@argonautica_person) %> |
<%= link_to 'Back', argonautica_people_path %>